#define SERVER_ECONOMY_FUNCS



#define SERVER_ECONOMY_TABLE_NAME      "server_economies"
#define DEFAULT_COMPONENT_PRICE        1
#define DEFAULT_MATERIAL_PRICE         10
#define DEFAULT_TREATMENT_PRICE        100
#define DEF_RENT_VEH_DAMAGED_FORFEIT   1.000
#define DEF_RENT_VEH_OVERTIME_FORFEIT  100
#define DEF_RENT_VEH_DESTROYED_FORFEIT 100


enum E_SERVER_ECONOMY
{
  ORM:ORM,
  SQL_ID,
  SUPPLY,
  RESERVE,
  INFLATION_RATE,
  SALES_TAX_RATE,
  MAX_FACTION_SALARY_WEEKLY,
  TREATMENT_PRICE,
  COMPONENT_PRICE,
  MATERIAL_PRICE,
  RENT_VEH_OVERTIME_FORFEIT,
  RENT_VEH_DESTROYED_FORFEIT,
  Float:RENT_VEH_DAMAGED_FORFEIT,
  CREATED_AT,
  UPDATED_AT,
  DELETED_AT
};

enum E_SERVER_ECONOMY_FLOW
{
  ECONOMY_FLOW_NONE = 0,
  ECONOMY_ADD_SUPPLY,
  ECONOMY_TAKE_SUPPLY
};

enum E_SERVER_ECONOMY_ACTION
{
  ECONOMY_ACTION_NONE = 0,
  ECONOMY_ACTION_DEFLATE,
  ECONOMY_ACTION_INFLATE
};



new ServerEconomy[E_SERVER_ECONOMY];
new TempServerEconomy[E_SERVER_ECONOMY];
new string:EconomySummary[768];