#define BODY_PART_TORSO                 (3)
#define BODY_PART_GROIN                 (4)
#define BODY_PART_RIGHT_ARM             (6)
#define BODY_PART_LEFT_ARM              (5)
#define BODY_PART_RIGHT_LEG             (8)
#define BODY_PART_LEFT_LEG              (7)
#define BODY_PART_HEAD                  (9)